CREATE DATABASE AddressBook;
use AddressBook;
CREATE TABLE AddressBook 
(ID int IDENTITY(1,1) PRIMARY KEY (ID),
FIRSTNAME varchar(50),
LASTNAME varchar(50),
ADDRESSs varchar(100),
CITY varchar(50),
STATE varchar(50),
ZIP varchar(6),
PHONENO varchar(12),
EMAIL varchar(50));
SELECT * FROM AddressBook;
INSERT INTO AddressBook VALUES('CHITTI','KATHI','7/42,VONTIMITTA','KADAPA','ANDHRA PRADESH',516213,9876543212,'chitti@gmail.com');
INSERT INTO AddressBook VALUES('SISIRA','KATHI','7/53,VONTIMITTA','KADAPA','ANDHRA PRADESH',516213,8765432123,'sisira@gmail.com');
SELECT * FROM AddressBook WHERE FIRSTNAME = 'PRASANNS';
UPDATE AddressBook SET State = 'KARNATAKA' WHERE FIRSTNAME = 'PRASANNA';
SELECT * FROM AddressBook WHERE City = 'KADAPA';
SELECT * FROM AddressBook WHERE State = 'ANDHRA PRADESH';


