CREATE DATABASE AddressBook;
use AddressBook;

-------UC=2----------
CREATE TABLE AddressBook 
(ID int IDENTITY(1,1) PRIMARY KEY (ID),
FIRSTNAME varchar(50),
LASTNAME varchar(50),
ADDRESSs varchar(100),
CITY varchar(50),
STATE varchar(50),
ZIP varchar(6),
PHONENO varchar(12),
EMAIL varchar(50));

----------UC=3---------

INSERT INTO AddressBook(FIRSTNAME,LASTNAME,ADDRESSs,CITY,STATE,ZIP,PHONENO,EMAIL) VALUES ('PRASANNA','KATHI','7/42,VONTIMITTA','KADAPA','ANDHRA PRADESH',516213,9703088064,'prasanna@gmail.com');

SELECT * FROM AddressBook;
INSERT INTO AddressBook VALUES('CHITTI','KATHI','7/42,VONTIMITTA','KADAPA','ANDHRA PRADESH',516213,9876543212,'chitti@gmail.com');
INSERT INTO AddressBook VALUES('SISIRA','KATHI','7/53,VONTIMITTA','KADAPA','ANDHRA PRADESH',516213,8765432123,'sisira@gmail.com');

----uc=4--------
SELECT * FROM AddressBook WHERE FIRSTNAME = 'PRASANNS';
UPDATE AddressBook SET State = 'KARNATAKA' WHERE FIRSTNAME = 'PRASANNA';

----uc=5--------
DELETE FROM AddressBook WHERE FIRSTNAME = 'PRASANNA';

----uc=6--------
SELECT * FROM AddressBook WHERE City = 'KADAPA';
SELECT * FROM AddressBook WHERE State = 'ANDHRA PRADESH';

----uc=7--------
SELECT COUNT(*) FROM AddressBook WHERE State = 'ANDHRA PRADESH';
SELECT COUNT(*) FROM AddressBook WHERE City = 'KADAPA';

----uc=8--------
SELECT * FROM AddressBook ORDER BY FIRSTNAME;

----uc=9--------
ALTER TABLE AddressBook ADD Type VARCHAR(20);
UPDATE AddressBook SET Type='FRIENDS' WHERE FIRSTNAME = 'SISIRA';
UPDATE AddressBook SET Type='FAMILY' WHERE FIRSTNAME = 'CHITTI' AND LASTNAME = 'KATHI';
UPDATE AddressBook SET Type='FAMILY' WHERE FIRSTNAME = 'PRASANNA' OR FIRSTNAME = 'KATHI';
SELECT * FROM AddressBook;

----uc=10--------
SELECT TYPE, COUNT(TYPE) AS TYPE_COUNT FROM AddressBook GROUP BY TYPE;

----uc=11--------
INSERT INTO AddressBook VALUES('ARJUN','MALLI','7/45','KADAPA','ANDHRA PRADESH',516213,9876543212,'arjun@gmail.com','FRIENDS')
INSERT INTO AddressBook VALUES('DIMPLE','KUNCHE','43B','MUMBAI','MAHARASTRA',456789,8765432124,'dimple@gmail.com','FRIENDS')
INSERT INTO AddressBook VALUES('ARJUN','MALLI','7/45','KADAPA','ANDHRA PRADESH',516213,9876543212,'arjun@gmail.com','FAMILY')
INSERT INTO AddressBook VALUES('VARA','KATHI','78/56','CHITTOR','ANDHRA PRADESH',654321,8765432123,'vara@gmail.com','FAMILY')
SELECT * FROM AddressBook;

----uc=12--------
CREATE TABLE CONTACT_TYPE
(TYPE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(25) NOT NULL)

INSERT INTO CONTACT_TYPE VALUES('FAMILY'),('FRIENDS'),('COLLEAGUES')
SELECT * FROM CONTACT_TYPE

CREATE TABLE PERSON_ADDRESS(
CONTACT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR(25) NOT NULL,
LASTNAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIPCODE FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TYPE_ID INT NOT NULL)

INSERT INTO PERSON_ADDRESS VALUES('PRASU','KATHI','7/42','KADAPA','ANDHRA PRADESH',516213,'prasu@gmail.com',1)
INSERT INTO PERSON_ADDRESS VALUES('LAKSHMI','KOMMURI','6/45','PORUMAMILLA','ANDHRA PRADESH',234567,'lakshmi@gmail.com',2)
INSERT INTO PERSON_ADDRESS VALUES('SRAVANTHI','BALA','4/65','BADWEL','ANDHRA PRADESH',456789,'sravanthi@gmail.com',1)
INSERT INTO PERSON_ADDRESS VALUES('BHARGAV','MUDDINA','8/56','CHITTOR','ANDHRA PRADESH',789234,'bhargav@gmail.com',1)
INSERT INTO PERSON_ADDRESS VALUES('MAHALAKSHMI','KATHI','3/42','VONTIMITTA','KARNATAKA',560045,'maha@gmail.com',3)
INSERT INTO PERSON_ADDRESS VALUES('VARA','MUDDINA','8/54','PILER','ANDHRA PRADESH',524321,'vara@gmail.com',3)
INSERT INTO PERSON_ADDRESS VALUES('DIMPLE','KUNCHE','22/3','MUMBAI','MAHARASTRA',678901,'dimple@gmail.com',2)

SELECT * FROM PERSON_ADDRESS

CREATE TABLE PERSON_PHONE
(CONTACT_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
PHONE_1 FLOAT NOT NULL,
PHONE_2 FLOAT NULL)
INSERT INTO PERSON_PHONE VALUES(1,'CHITTI',9876543212,9876234567)
INSERT INTO PERSON_PHONE VALUES(3,'SISIRA',87654321234,76543212345)
INSERT INTO PERSON_PHONE VALUES(4,'BHARGAVA',9123456789,7654321234)
INSERT INTO PERSON_PHONE VALUES(5,'ARJUN',8765234567,7908645231)
INSERT INTO PERSON_PHONE (CONTACT_ID,FIRST_NAME,PHONE_1) VALUES(6,'MALLI',6005526294)
INSERT INTO PERSON_PHONE VALUES(7,'SRAVANTHI',6123456789,6795321405)
INSERT INTO PERSON_PHONE VALUES(8,'LAKSHMI',9573148337,8755428901)
SELECT * FROM PERSON_PHONE

ALTER TABLE PERSON_ADDRESS ADD CONSTRAINT FK_CONTACT_TYPE FOREIGN KEY(TYPE_ID) REFERENCES CONTACT_TYPE(TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE PERSON_PHONE ADD CONSTRAINT FK_PERSON_PHONE FOREIGN KEY(PERSON_ID) REFERENCES PERSON_ADDRESS(CONTACT_ID) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE PERSON_PHONE ADD PERSON_ID INT 

----UC=13----------
SELECT * FROM PERSON_ADDRESS WHERE CITY = 'KADAPA'
SELECT * FROM PERSON_ADDRESS WHERE STATE = 'ANDHRA PRADESH'

SELECT CITY, COUNT(CITY) AS CONTACT_ADDRESS FROM AddressBook GROUP BY CITY
SELECT STATE, COUNT(STATE) AS CONTACT_ADDRESS FROM AddressBook GROUP BY STATE

SELECT * FROM PERSON_ADDRESS WHERE CITY = 'KADAPA' ORDER BY FIRSTNAME 

SELECT TYPE_NAME,COUNT(TYPE_NAME) FROM CONTACT_TYPE CT INNER JOIN PERSON_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID GROUP BY TYPE_NAME
SELECT TYPE_NAME,CA.FIRSTNAME,PHONE_1 FROM CONTACT_TYPE CT INNER JOIN PERSON_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID INNER JOIN PERSON_PHONE CP ON CA.CONTACT_ID = CP.CONTACT_ID



